Extend the API Key model
geosolutions-it/djam pull request #27
Opened 2024-09-09 12:23 UTC by Gpetrak

Extension of the API key model with the fields:

- `expiry`
- `scope`

As described in [this issue](https://github.com/geosolutions-it/djam/issues/26)

2024-09-09 13:37 UTC, Gpetrak commented on project/apps/identity_provider/settings.py
> +APIKEY_EXPIRE = datetime.timedelta(days=30)
Thanks @mattiagiupponi I pushed the recommended change.

2024-09-10 12:48 UTC, mattiagiupponi requested changes

2024-09-10 12:48 UTC, mattiagiupponi commented on project/apps/identity_provider/models.py
> +    scope = models.CharField(max_length=50, blank=False, null=False, choices=scopeChoices, default='resource')
If the scope have a choice, i think is better to not give a default, but instead who save the key should define the scope of it

2024-09-10 12:48 UTC, mattiagiupponi commented on project/apps/identity_provider/models.py
> +            return (timezone.now() + APIKEY_EXPIRE)
typo: here there is an indentation issue

2024-09-10 15:04 UTC, merged